version: '2.1'

services:
  qianjiangyuan:
    image: qianjiangyuan
    build: .
    environment:
      NODE_ENV: development
    ports:
      - {{cnf[webuiport]}}:{{cnf[webuiport]}}
      - 9229:9229
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 index.js